# -*- coding: utf-8 -*-
"""Auto-encoders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hc9Igb53aQFQ2cYKCShejgRSZilJZdj5
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

# Custom preprocessing functions

def load_image(image_path):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_image(image, channels=3)
    return image

def resize_image(image, size=(224, 224)):
    image = tf.image.resize(image, size)
    return image

def normalize_image(image):
    image = tf.cast(image, tf.float32) / 255.0
    return image

def augment_image(image):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_brightness(image, max_delta=0.1)
    image = tf.image.random_contrast(image, lower=0.9, upper=1.1)
    return image

def convert_to_grayscale(image):
    image = tf.image.rgb_to_grayscale(image)
    return image

def convert_color_space(image):
    # Ensure image has 3 channels (RGB)
    image = tf.cond(tf.shape(image)[-1] == 1,
                    lambda: tf.image.grayscale_to_rgb(image),
                    lambda: image)
    # Convert to YUV color space
    image = tf.image.rgb_to_yuv(image)
    return image

def apply_gaussian_blur(image):
    image = tf.expand_dims(image, axis=0)  # Add batch dimension
    image = tf.cast(image, tf.float32)  # Ensure image is in float32 format
    image_blur = tf.image.resize(image, (image.shape[1]//2, image.shape[2]//2))  # Resize image to half its size
    image_blur = tf.image.resize(image_blur, (image.shape[1], image.shape[2]))  # Resize image back to original size (applies blur effect)
    return tf.squeeze(image_blur, axis=0)  # Remove batch dimension

def equalize_histogram(image):
    # Convert image to 8-bit unsigned integer format if necessary
    if image.dtype != np.uint8:
        image = tf.image.convert_image_dtype(image, tf.uint8)
    # Ensure image is in grayscale format
    if image.shape[-1] == 3:
        image = tf.image.rgb_to_grayscale(image)
    # Apply histogram equalization
    image = cv2.equalizeHist(image.numpy())
    return tf.convert_to_tensor(image)

def adjust_channels(image):
    # Add batch dimension
    image = tf.expand_dims(image, axis=0)
    # Adjust brightness and contrast
    image = tf.image.adjust_brightness(image, delta=0.1)
    image = tf.image.adjust_contrast(image, contrast_factor=1.2)
    # Remove batch dimension
    image = tf.squeeze(image, axis=0)
    return image

def clip_image(image):
    # Convert image to float32
    image = tf.image.convert_image_dtype(image, tf.float32)
    # Clip pixel values to the range [0, 1]
    image = tf.clip_by_value(image, clip_value_min=0.0, clip_value_max=1.0)
    return image

def zero_center_image(image):
    mean = tf.reduce_mean(image)
    image = image - mean
    return image

def standardize_image(image):
    image = tf.image.per_image_standardization(image)
    return image

def apply_mask(image, mask):
    image = image * mask
    return image

def pad_image(image, padding_size=(10, 10)):
    return tf.pad(image, [[padding_size[0], padding_size[0]], [padding_size[1], padding_size[1]], [0, 0]])

# Combined preprocessing function
def custom_preprocessing(image):
    image = resize_image(image)
    image = normalize_image(image)
    image = augment_image(image)
    image = convert_to_grayscale(image) # Uncomment if grayscale conversion is needed
    image = convert_color_space(image) # Uncomment if color space conversion is needed
    image = apply_gaussian_blur(image)
    image = equalize_histogram(image)
    image = adjust_channels(image)
    image = clip_image(image)
    image = zero_center_image(image)
    image = standardize_image(image)
    # Assuming mask is provided, otherwise mask step is skipped
    # mask = ...
    # image = apply_mask(image, mask)
    image = pad_image(image)
    return image

def show_images(images, titles):
    num_images = len(images)
    num_columns = 3
    num_rows = (num_images + num_columns - 1) // num_columns

    fig, axes = plt.subplots(num_rows, num_columns, figsize=(15, 5*num_rows))

    for i, ax in enumerate(axes.flat):
        if i < num_images:
            ax.imshow(images[i])
            if titles and i < len(titles):
                ax.set_title(titles[i])
            ax.axis('off')
        else:
            ax.axis('off')

    plt.tight_layout()
    plt.show()

# Define paths to your training and validation directories
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define paths to your training and validation directories
train_dir = '/content/drive/MyDrive/internship (Xebia)/Training'
validation_dir = '/content/drive/MyDrive/internship (Xebia)/Validation'

# Create an ImageDataGenerator instance with the custom preprocessing function
datagen = ImageDataGenerator(preprocessing_function=custom_preprocessing)

# Load images from directory using ImageDataGenerator
def preprocess_images_from_directory(directory, target_size=(224, 224), batch_size=32, is_training=True):
    datagen = ImageDataGenerator(
        preprocessing_function=custom_preprocessing)

    generator = datagen.flow_from_directory(
        directory,
        target_size=target_size,
        batch_size=batch_size,
        class_mode='categorical')

    return generator

# Create generators for training and validation with additional preprocessing
train_generator = preprocess_images_from_directory(train_dir, is_training=True)
validation_generator = preprocess_images_from_directory(validation_dir, is_training=False)

import matplotlib.pyplot as plt
import tensorflow as tf

# Define custom preprocessing functions (as provided earlier)
def load_image(image_path):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_image(image, channels=3)
    return image

def resize_image(image, size=(224, 224)):
    image = tf.image.resize(image, size)
    return image

def normalize_image(image):
    image = tf.cast(image, tf.float32) / 255.0
    return image

def augment_image(image):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_brightness(image, max_delta=0.1)
    image = tf.image.random_contrast(image, lower=0.9, upper=1.1)
    return image

def convert_to_grayscale(image):
    image = tf.image.rgb_to_grayscale(image)
    return image

def convert_color_space(image):
    image = tf.cond(tf.shape(image)[-1] == 1,
                    lambda: tf.image.grayscale_to_rgb(image),
                    lambda: image)
    image = tf.image.rgb_to_yuv(image)
    return image

def apply_gaussian_blur(image):
    image = tf.expand_dims(image, axis=0)
    image = tf.cast(image, tf.float32)
    image_blur = tf.image.resize(image, (image.shape[1]//2, image.shape[2]//2))
    image_blur = tf.image.resize(image_blur, (image.shape[1], image.shape[2]))
    return tf.squeeze(image_blur, axis=0)

def equalize_histogram(image):
    if image.dtype != tf.uint8:
        image = tf.image.convert_image_dtype(image, tf.uint8)
    if image.shape[-1] == 3:
        image = tf.image.rgb_to_grayscale(image)
    image = cv2.equalizeHist(image.numpy())
    return tf.convert_to_tensor(image, dtype=tf.uint8)

def adjust_channels(image):
    image = tf.expand_dims(image, axis=0)
    image = tf.image.adjust_brightness(image, delta=0.1)
    image = tf.image.adjust_contrast(image, contrast_factor=1.2)
    image = tf.squeeze(image, axis=0)
    return image

def clip_image(image):
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.clip_by_value(image, clip_value_min=0.0, clip_value_max=1.0)
    return image

def zero_center_image(image):
    mean = tf.reduce_mean(image)
    image = image - mean
    return image

def standardize_image(image):
    image = tf.image.per_image_standardization(image)
    return image

example_image_path = '/content/drive/MyDrive/internship (Xebia)/Training/Scarlett Johansson/003_b416eed5.jpg'
example_image = load_image(example_image_path)

preprocessing_steps = [
    ('Original Image', example_image),
    ('Resized Image', resize_image(example_image)),
    ('Normalized Image', normalize_image(resize_image(example_image))),
    ('Augmented Image', augment_image(normalize_image(resize_image(example_image)))),
    ('Grayscale Image', convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))),
    ('YUV Color Space', convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))),
    ('Gaussian Blur', apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))))),
    ('Equalized Histogram', equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))),
    ('Adjusted Channels', adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))))))),
    ('Clipped Image', clip_image(adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))))),
    ('Zero-Centered Image', zero_center_image(clip_image(adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))))))
]

titles = [
    'Original Image',
    'Resized Image',
    'Normalized Image',
    'Augmented Image',
    'Grayscale Image',
    'YUV Color Space',
    'Gaussian Blur',
    'Equalized Histogram',
    'Adjusted Channels',
    'Clipped Image',
    'Zero-Centered Image'
]

# Ensure the number of titles matches the number of preprocessing steps
assert len(titles) == len(preprocessing_steps)

# Display the images
for title, (step_name, image) in zip(titles, preprocessing_steps):
    plt.figure(figsize=(8, 8))
    if step_name == 'Equalized Histogram':
        image = tf.convert_to_tensor(image, dtype=tf.uint8)
        image = tf.image.convert_image_dtype(image, dtype=tf.float32)
    plt.imshow(image, cmap='gray' if step_name == 'Grayscale Image' else None)
    plt.title(title)
    plt.axis('off')
    plt.show()

import matplotlib.pyplot as plt
import tensorflow as tf

example_image_path = '/content/drive/MyDrive/internship (Xebia)/Training/Scarlett Johansson/003_b416eed5.jpg'
example_image = load_image(example_image_path)

# Apply preprocessing steps
preprocessing_steps = [
    ('Original Image', example_image),
    ('Resized Image', resize_image(example_image)),
    ('Normalized Image', normalize_image(resize_image(example_image))),
    ('Augmented Image', augment_image(normalize_image(resize_image(example_image)))),
    ('Grayscale Image', convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))),
    ('YUV Color Space', convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))),
    ('Gaussian Blur', apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))))),
    ('Equalized Histogram', equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))),
    ('Adjusted Channels', adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image))))))))),
    ('Clipped Image', clip_image(adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))))),
    ('Zero-Centered Image', zero_center_image(clip_image(adjust_channels(equalize_histogram(apply_gaussian_blur(convert_color_space(convert_to_grayscale(augment_image(normalize_image(resize_image(example_image)))))))))))
]

# Titles for the preprocessing steps
titles = [
    'Original Image',
    'Resized Image',
    'Normalized Image',
    'Augmented Image',
    'Grayscale Image',
    'YUV Color Space',
    'Gaussian Blur',
    'Equalized Histogram',
    'Adjusted Channels',
    'Clipped Image',
    'Zero-Centered Image'
]

# Ensure that the number of titles matches the number of preprocessing steps
assert len(titles) == len(preprocessing_steps)

# Display the images
for title, (step_name, image) in zip(titles, preprocessing_steps):
    plt.figure(figsize=(8, 8))
    if step_name == 'Equalized Histogram':
        # Equalize histogram produces a numpy array, need to convert it back to tensor and then to float32
        image = tf.convert_to_tensor(image, dtype=tf.uint8)
        image = tf.image.convert_image_dtype(image, dtype=tf.float32)
    plt.imshow(image, cmap='gray' if step_name == 'Grayscale Image' else None)
    plt.title(title)
    plt.axis('off')
    plt.show()

"""pre-trained model for auto encoders

build auto encoder
"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D

def build_autoencoder(input_shape):
    input_img = Input(shape=input_shape)

    # Encoder
    x = Conv2D(32, (3, 3), activation='relu', padding='same')(input_img)
    x = MaxPooling2D((2, 2), padding='same')(x)
    x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    encoded = MaxPooling2D((2, 2), padding='same')(x)

    # Decoder
    x = Conv2D(64, (3, 3), activation='relu', padding='same')(encoded)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    decoded = Conv2D(3, (3, 3), activation='sigmoid', padding='same')(x)

    autoencoder = Model(input_img, decoded)
    autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

    return autoencoder

input_shape = (224, 224, 3)  # Adjust based on your image dimensions
autoencoder = build_autoencoder(input_shape)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Directory containing your training images
training_directory = '/content/drive/MyDrive/internship (Xebia)/Training'
validation_directory = '/content/drive/MyDrive/internship (Xebia)/Validation'
datagen = ImageDataGenerator(rescale=0.5)  # Rescaling for normalization

train_generator = datagen.flow_from_directory(
    training_directory,
    target_size=(224, 224),
    batch_size=32,
    class_mode='input'  # Use 'input' since we're training an autoencoder
)
validation_datagen = ImageDataGenerator(rescale=1./255)

train_generator = datagen.flow_from_directory(
    training_directory,
    target_size=(224, 224),
    batch_size=32,
    class_mode='input'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_directory,
    target_size=(224, 224),
    batch_size=32,
    class_mode='input'
)

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

# Define the autoencoder model
input_dim = 784  # Example for a flattened 28x28 image
encoding_dim = 64

input_layer = Input(shape=(input_dim,))
encoded = Dense(encoding_dim, activation='relu')(input_layer)
decoded = Dense(input_dim, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)

# Compile the model
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

# Display the model summary
autoencoder.summary()

import numpy as np

x_train = np.random.random((100, input_dim))
history=autoencoder.fit(
    x_train,
    x_train,
    epochs=50,
    batch_size=3,
    steps_per_epoch=3,  # Run 3 batches per epoch
    verbose=1
)

"""define a function to extract features"""

for i, layer in enumerate(autoencoder.layers):
    print(i, layer.name, layer.output_shape)

from tensorflow.keras.models import Model

# Create a model to extract features using the encoder part of the autoencoder
encoder = Model(inputs=autoencoder.input, outputs=autoencoder.layers[1].output)


def extract_autoencoder_features(image_path, model):
    # Load and preprocess the image
    img = keras_image.load_img(image_path, target_size=(224, 224))
    x = keras_image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x / 255.0  # Normalize the image

    # Extract features using the encoder part of the autoencoder
    features = model.predict(x)
    return features

"""Extract Features from Images in Subdirectories"""

!pip install keras
from tensorflow.keras.preprocessing import image as keras_image # Import the keras_image module

# ... (rest of your code)

import os
from tensorflow.keras.preprocessing import image as keras_image
import numpy as np

def extract_autoencoder_features(image_path, model):
    # Load and preprocess the image
    img = keras_image.load_img(image_path, target_size=(28, 28), color_mode='grayscale')  # Adjust target size and color mode if necessary
    x = keras_image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x / 255.0  # Normalize the image

    # Flatten the image
    x = x.reshape((1, 784))

    # Extract features using the encoder part of the autoencoder
    features = model.predict(x)
    return features

def extract_features_from_directory(directory_path, model):
    features_list = []
    for subdir, _, files in os.walk(directory_path):
        for file in files:
            image_path = os.path.join(subdir, file)
            if image_path.lower().endswith(('.png', '.jpg', '.jpeg')):
                print(f"Processing image: {image_path}")  # Debug statement
                features = extract_autoencoder_features(image_path, model)
                if features is not None:
                    features_list.append(features)
                else:
                    print(f"Failed to extract features from image: {image_path}")  # Debug statement
    return np.array(features_list)

# Paths to your directories
training_directory = '/content/drive/MyDrive/internship (Xebia)/Training'
validation_directory = '/content/drive/MyDrive/internship (Xebia)/Validation'

# Extract features from all images in the training directory
train_features = extract_features_from_directory(training_directory, encoder)

# Extract features from all images in the validation directory
validation_features = extract_features_from_directory(validation_directory, encoder)

print("Extracted features shape for each image:", [feature.shape for feature in train_features])
print("Train features shape:", train_features.shape)
print("Validation features shape:", validation_features.shape)

from sklearn.cluster import KMeans

# Combine features from train and validation sets for clustering
all_features = np.vstack((train_features, validation_features))

# Reshape the features to 2D
all_features = all_features.reshape(all_features.shape[0], -1) # Reshape to (number of samples, number of features)

# Apply KMeans clustering
num_clusters = 5  # Adjust the number of clusters as needed
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(all_features)

# Get cluster labels
train_labels = kmeans.predict(train_features.reshape(train_features.shape[0], -1)) # Reshape train_features before prediction
validation_labels = kmeans.predict(validation_features.reshape(validation_features.shape[0], -1)) # Reshape validation_features before prediction

print("Train cluster labels:", train_labels)
print("Validation cluster labels:", validation_labels)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

# Reduce dimensionality for visualization
tsne = TSNE(n_components=2, random_state=42)
reduced_features = tsne.fit_transform(all_features)

# Split reduced features back into train and validation sets
train_reduced = reduced_features[:len(train_features)]
validation_reduced = reduced_features[len(train_features):]

# Plot the results
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.scatter(train_reduced[:, 0], train_reduced[:, 1], c=train_labels, cmap='viridis', marker='o')
plt.title('Train Set Clustering')
plt.xlabel('t-SNE Component 1')
plt.ylabel('t-SNE Component 2')
plt.colorbar(label='Cluster')

plt.subplot(1, 2, 2)
plt.scatter(validation_reduced[:, 0], validation_reduced[:, 1], c=validation_labels, cmap='viridis', marker='o')
plt.title('Validation Set Clustering')
plt.xlabel('t-SNE Component 1')
plt.ylabel('t-SNE Component 2')
plt.colorbar(label='Cluster')

plt.show()

"""LOADING MOBILENETV2 MODEL"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Load the base model
base_model = MobileNetV2(weights='imagenet', include_top=False)

# Add a global spatial average pooling layer
x = base_model.output
x = GlobalAveragePooling2D()(x)

# Add a fully connected layer
x = Dense(1024, activation='relu')(x)

# Add a logistic layer for the number of classes (adjust the number of classes)
num_classes = 5  # Adjust this based on your dataset
predictions = Dense(num_classes, activation='softmax')(x)

# Construct the final model
model = Model(inputs=base_model.input, outputs=predictions)

# Freeze the base layers
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Create data generators for training and validation
train_datagen = ImageDataGenerator(
    rescale=1.0/255.0,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1.0/255.0)

train_generator = train_datagen.flow_from_directory(
    '/content/drive/MyDrive/internship (Xebia)/Training',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

val_generator = val_datagen.flow_from_directory(
    '/content/drive/MyDrive/internship (Xebia)/Validation',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

# Train the model
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    validation_data=val_generator,
    validation_steps=val_generator.samples // val_generator.batch_size,
    epochs=15
)

# Evaluate the model on the validation set
val_loss, val_accuracy = model.evaluate(val_generator, steps=val_generator.samples // val_generator.batch_size)
print(f'Validation Accuracy: {val_accuracy * 100:.2f}%')

import matplotlib.pyplot as plt

# Plot training & validation accuracy values
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.show()

"""REMOVING OVERFITTING"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model

# Load the base model
base_model = MobileNetV2(weights='imagenet', include_top=False)

# Add a global spatial average pooling layer
x = base_model.output
x = GlobalAveragePooling2D()(x)

# Add a fully connected layer and Dropout
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)  # Add Dropout layer

# Add a logistic layer for the number of classes (adjust the number of classes)
num_classes = 5  # Adjust this based on your dataset
predictions = Dense(num_classes, activation='softmax')(x)

# Construct the final model
model = Model(inputs=base_model.input, outputs=predictions)

# Freeze the base layers
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Create data generators for training and validation
train_datagen = ImageDataGenerator(
    rescale=1.0/255.0,
    shear_range=0.2,
    zoom_range=0.2,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1.0/255.0)

train_generator = train_datagen.flow_from_directory(
    '/content/drive/MyDrive/internship (Xebia)/Training',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

val_generator = val_datagen.flow_from_directory(
    '/content/drive/MyDrive/internship (Xebia)/Validation',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Define callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.h5', save_best_only=True, monitor='val_loss', mode='min')

# Train the model with callbacks
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    validation_data=val_generator,
    validation_steps=val_generator.samples // val_generator.batch_size,
    epochs=50,
    callbacks=[early_stopping, model_checkpoint]
)

# Unfreeze the top layers of the model for fine-tuning
for layer in base_model.layers[-30:]:
    layer.trainable = True

# Recompile the model with a lower learning rate
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model again with the unfrozen layers
history_fine = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    validation_data=val_generator,
    validation_steps=val_generator.samples // val_generator.batch_size,
    epochs=20,
    callbacks=[early_stopping, model_checkpoint]
)

# Evaluate the model on the validation set
val_loss, val_accuracy = model.evaluate(val_generator, steps=val_generator.samples // val_generator.batch_size)
print(f'Validation Accuracy: {val_accuracy * 100:.2f}%')

# Plot training & validation accuracy values
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'] + history_fine.history['accuracy'])
plt.plot(history.history['val_accuracy'] + history_fine.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'] + history_fine.history['loss'])
plt.plot(history.history['val_loss'] + history_fine.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.show()

from tensorflow.keras.models import load_model
import numpy as np

# Load the best model
model = load_model('best_model.h5')

# Remove the final classification layer to create a feature extractor
feature_extractor = Model(inputs=model.input, outputs=model.layers[-3].output)

# Function to extract features using the feature extractor
def extract_features(generator):
    features = []
    labels = []
    for inputs, label in generator:
        feature = feature_extractor.predict(inputs)
        features.append(feature)
        labels.append(label)
        if len(features) * generator.batch_size >= generator.samples:
            break
    return np.vstack(features), np.vstack(labels)

# Extract features from training and validation sets
train_features, train_labels = extract_features(train_generator)
val_features, val_labels = extract_features(val_generator)

"""APPLYING KMEANS CLUSTERING"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Combine features from training and validation sets for clustering
all_features = np.vstack((train_features, val_features))

# Determine the optimal number of clusters (using the Elbow method)
inertia = []
for n_clusters in range(1, 11):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(all_features)
    inertia.append(kmeans.inertia_)

# Plot the elbow curve
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Elbow Method for Optimal Number of Clusters')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.show()

# Choose the number of clusters (e.g., 5) based on the elbow plot
optimal_clusters = 5

# Apply KMeans with the optimal number of clusters
kmeans = KMeans(n_clusters=optimal_clusters, random_state=42)
kmeans.fit(all_features)

# Get the cluster labels
cluster_labels = kmeans.labels_

# Add cluster labels to each image for further analysis
train_cluster_labels = cluster_labels[:len(train_features)]
val_cluster_labels = cluster_labels[len(train_features):]

# Print the cluster centers
print("Cluster centers:\n", kmeans.cluster_centers_)

from sklearn.manifold import TSNE

# Perform t-SNE to reduce dimensionality for visualization
tsne = TSNE(n_components=2, random_state=42)
tsne_results = tsne.fit_transform(all_features)

# Plot the t-SNE results with cluster labels
plt.figure(figsize=(12, 8))
for i in range(optimal_clusters):
    indices = cluster_labels == i
    plt.scatter(tsne_results[indices, 0], tsne_results[indices, 1], label=f'Cluster {i}')
plt.legend()
plt.title('t-SNE Visualization of KMeans Clusters')
plt.show()

"""MODEL DEPLOYMENT"""

# Assuming 'model' is your trained model and 'kmeans' is your KMeans model
model.save('trained_model.h5')

from tensorflow.keras.models import load_model

# Load the trained model
model = load_model('trained_model.h5')

!pip install flask-ngrok

from flask import Flask, request, jsonify
from tensorflow.keras.models import load_model as tf_load_model # Rename imported function
import numpy as np
from tensorflow.keras.preprocessing import image as keras_image

app = Flask(__name__)
model = None  # Define model globally

# Load the trained model
def load_model():
    global model
    model = tf_load_model('trained_model.h5')  # Use renamed function

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json(force=True)
    image_path = data['image_path']

    # Perform prediction
    prediction = predict_image(image_path)

    return jsonify({'prediction': prediction.tolist()})

def preprocess_image(image_path):
    # Load and preprocess the image
    # Example preprocessing steps (adjust as per your training preprocessing)
    img = keras_image.load_img(image_path, target_size=(224, 224))
    x = keras_image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x / 255.0  # Normalize the image

    return x

def predict_image(image_path):
    x = preprocess_image(image_path)
    prediction = model.predict(x)
    return prediction

if __name__ == '__main__':
    load_model()  # Load the model when the app starts
    app.run(host='0.0.0.0', port=5000)

from flask_ngrok import run_with_ngrok

# Enable ngrok and run the app
run_with_ngrok(app)
app.run()